### ISSUE TITLE
Некорректное именование

### ISSUE THREAD

**Issue by casa7x** [xydoy92/lesson_12#1]
https://github.com/xydoy92/lesson_12/blob/fabbecda894a7c8df30eebff17cbfd38fee05766/script.js#L4

Что значит твой номер, твой плюс, твой минус. Мне как разработчику непонятно это. наименование должно отражать суть в коде и абстрактно понятным быть. К примеру yourNumber => userInitialNumber, yourPlus => userNumberToAdd.

Тоже самое и во второй задаче. justANumber. Я понимаю, что простенькая задача. Но всегда подходить надо к решению серьёзно и представлять, что после тебя этот код может использоваться. Как минмум его читаю я.  Не justANumber, а к примеру numberTypeValue

**Comment by xydoy92** [comment]
Спасибо, сейчас поправлю

**Comment by xydoy92** [comment]
Исправил)
